version: '2'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '1337:1337'
      - '4999:4999'
    links:
      - mongo
  mongo:
    container_name: mongo
    build: './mongo'
    ports:
      - '27017:27017'
